- biodata-models/src/main/java/org/opencb/biodata/models/variant/VariantAggregatedVcfFactory.java
- biodata-models/src/main/java/org/opencb/biodata/models/variant/VariantVcfExacFactory.java
- biodata-models/src/test/java/org/opencb/biodata/models/variant/VariantAggregatedVcfFactoryTest.java
- biodata-models/src/test/java/org/opencb/biodata/models/variant/VariantVcfExacFactoryTest.java
- biodata-models/src/test/java/org/opencb/biodata/models/variant/VariantVcfFactoryTest.java
mainly, this improves the support of exac maf.
updated tests.
> models: ensuring MAF is calculated from AF or AC.

- biodata-models/src/main/java/org/opencb/biodata/models/variant/Variant.java
- biodata-models/src/test/java/org/opencb/biodata/models/variant/VariantTransformToEnsemblFormatTest.java
Take into account normalized variants.
Added tests as well.
> fixed bug in Variant.transformToEnsemblFormat

- biodata-models/src/main/java/org/opencb/biodata/models/variant/annotation/ConsequenceTypeMappings.java
- biodata-models/src/main/java/org/opencb/biodata/models/variant/annotation/exceptions/SOTermNotAvailableException.java
Added two consequence type mappings and a custom exception
> Added Consequence type Mappings

- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/VariantJsonReader.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/VariantNormalizer.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/VariantVcfHtsjdkReader.java
If one variant in a batch fails to normalise (within variant readers), the whole batch does no longer die, a warniing is issued and that variant is skipped
> Feature 398 phased variants

- biodata-models/pom.xml
- biodata-models/src/main/java/org/opencb/biodata/models/variant/stats/VariantSampleStats.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/stats/VariantSampleStatsCalculator.java
- biodata-tools/src/test/java/org/opencb/biodata/tools/variant/stats/writer/VariantStatsTsvExporterTest.java
- pom.xml
I am having compilation issues. Maybe I have a cached library? I can try to delete all my local JARs?
I compiled these locally:
biodata-hotfix-1.5.x
which needs commons - hotfix-3.7.x
Error 1:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project biodata-models: Compilation failure: Compilation failure: 
[ERROR] /home/julie/git/biodata/biodata-models/src/main/java/org/opencb/biodata/models/variant/stats/VariantSampleStats.java:[3,19] package javafx.util does not exist
[ERROR] /home/julie/git/biodata/biodata-models/src/main/java/org/opencb/biodata/models/variant/stats/VariantSampleStats.java:[25,18] cannot find symbol
[ERROR]   symbol:   class Pair
[ERROR]   location: class …
```
> fix Pair issue (again?)

- biodata-formats/pom.xml
- biodata-formats/src/main/java/org/opencb/biodata/formats/variant/annotation/io/VepFormatReader.java
- biodata-models/pom.xml
- biodata-models/src/main/java/org/opencb/biodata/models/clinical/pedigree/PedigreeManager.java
- biodata-models/src/main/java/org/opencb/biodata/models/variant/stats/IBDExpectedFrequencies.java
- biodata-models/src/test/java/org/opencb/biodata/models/clinical/interpretation/VariantClassificationTest.java
- biodata-tools/pom.xml
- biodata-tools/src/main/java/org/opencb/biodata/tools/alignment/BamUtils.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/clinical/ReportedVariantCreator.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/feature/WigUtils.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/converters/avro/VariantFileHeaderToVCFHeaderConverter.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/converters/ga4gh/Ga4ghVariantConverter.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/metadata/VariantMetadataUtils.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/stats/AggregationUtils.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/stats/VariantSampleStatsCalculator.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/stats/VariantSetStatsCalculator.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/stats/writer/VariantStatsTsvExporter.java
- biodata-tools/src/test/java/org/opencb/biodata/tools/sequence/fasta/SamtoolsFastaIndexTest.java
- biodata-tools/src/test/java/org/opencb/biodata/tools/variant/converters/VariantContextConverterTest.java
- pom.xml
patch dependency libraries by explicitly including in pox.xml
> include common-lang3 and commons-collections in pox.xml #TASK-1625

- biodata-tools/pom.xml
- biodata-tools/src/main/java/org/opencb/biodata/tools/alignment/BamManager.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/clinical/DefaultClinicalVariantCreator.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/clinical/TeamClinicalVariantCreator.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/pedigree/ModeOfInheritance.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/VariantJsonReader.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/stats/SampleVariantStatsCalculator.java
- biodata-tools/src/test/java/org/opencb/biodata/tools/variant/metadata/VariantMetadataManagerTest.java
> TASK-2094 - ClassNotFoundException: org.apache.commons.collections.CollectionUtils

- biodata-formats/pom.xml
- biodata-formats/src/main/java/org/opencb/biodata/formats/variant/annotation/io/VepFormatReader.java
- biodata-models/pom.xml
- biodata-models/src/main/java/org/opencb/biodata/models/clinical/pedigree/PedigreeManager.java
- biodata-models/src/main/java/org/opencb/biodata/models/variant/stats/IBDExpectedFrequencies.java
- biodata-models/src/test/java/org/opencb/biodata/models/clinical/interpretation/VariantClassificationTest.java
- biodata-tools/pom.xml
- biodata-tools/src/main/java/org/opencb/biodata/tools/alignment/BamUtils.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/clinical/ReportedVariantCreator.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/commons/ChunkFrequencyManager.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/feature/BigWigManager.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/feature/WigUtils.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/converters/avro/VariantFileHeaderToVCFHeaderConverter.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/converters/ga4gh/Ga4ghVariantConverter.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/metadata/VariantMetadataUtils.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/stats/AggregationUtils.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/stats/VariantSampleStatsCalculator.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/stats/VariantSetStatsCalculator.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/stats/writer/VariantStatsTsvExporter.java
- biodata-tools/src/test/java/org/opencb/biodata/tools/alignment/BamManagerTest.java
- biodata-tools/src/test/java/org/opencb/biodata/tools/commons/ChunkFrequencyManagerTest.java
- biodata-tools/src/test/java/org/opencb/biodata/tools/feature/BigWigManagerTest.java
- biodata-tools/src/test/java/org/opencb/biodata/tools/sequence/fasta/SamtoolsFastaIndexTest.java
- biodata-tools/src/test/java/org/opencb/biodata/tools/variant/converters/VariantContextConverterTest.java
- pom.xml
For a while I couldn't compile CellBase because of a missing dependency so I removed it (bigwig) from biodata completely. That dependency has been restored, so I would like to revert this change.
REVERT: https://github.com/opencb/biodata/pull/225
> REVERT removing bigwig

- biodata-models/src/main/java/org/opencb/biodata/models/clinical/qc/RelatednessReport.java
- biodata-models/src/main/java/org/opencb/biodata/models/clinical/qc/RelatednessScore.java
> TASK-2215 Fix family quality control (relatedness) when saving in OpenCGA catalog

- biodata-models/src/main/java/org/opencb/biodata/models/variant/Variant.java
- biodata-models/src/main/java/org/opencb/biodata/models/variant/VariantBuilder.java
- biodata-models/src/test/java/org/opencb/biodata/models/variant/VariantBuilderTest.java
> TASK-2342 - Error at variant-index "SQLException: ERROR 201 (22000): Illegal data"

- biodata-external/pom.xml
- biodata-formats/pom.xml
- biodata-models/pom.xml
- biodata-tools/pom.xml
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/converters/avro/VariantStatsToPopulationFrequencyConverter.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/merge/VariantAlternateRearranger.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/stats/VariantAggregatedEVSStatsCalculator.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/stats/VariantAggregatedExacStatsCalculator.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/variant/stats/VariantAggregatedStatsCalculator.java
- biodata-tools/src/test/java/org/opencb/biodata/tools/variant/converters/avro/VariantStatsToPopulationFrequencyConverterTest.java
- biodata-tools/src/test/java/org/opencb/biodata/tools/variant/stats/VariantAggregatedStatsCalculatorTest.java
- biodata-tools/src/test/resources/datasets/gnomad_genomes/gnomad.exomes.v2.1.1.sites.small.vcf
- biodata-tools/src/test/resources/datasets/gnomad_genomes/gnomad.genomes.v3.1.2.sites.small.vcf
- pom.xml
TASK-2294 - Include homalt count from aggregated vcf files
> TASK-2294 - Include homalt count from aggregated vcf files

- biodata-models/src/main/java/org/opencb/biodata/models/clinical/interpretation/CancerPanel.java
- biodata-models/src/main/java/org/opencb/biodata/models/clinical/interpretation/DiseasePanel.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/clinical/DiseasePanelParsers.java
> TASK-2549 - Role and modeOfInheritance changes in Panel data model

- .github/workflows/build-analysis.yml
- .github/workflows/develop.yml
- .github/workflows/release.yml
- .github/workflows/task.yml
> TASK-3953 - CI/CD in task.yml to deploy project dependencies

- biodata-models/src/main/java/org/opencb/biodata/models/clinical/ClinicalAnalyst.java
- biodata-models/src/main/java/org/opencb/biodata/models/clinical/interpretation/ClinicalVariant.java
- biodata-models/src/main/java/org/opencb/biodata/models/clinical/interpretation/MiniPubmed.java
- biodata-models/src/main/java/org/opencb/biodata/models/constants/FieldConstants.java
> TASK-5198 - Catalog changes to improve Clinical reports

- biodata-models/src/main/java/org/opencb/biodata/models/clinical/ClinicalAnalyst.java
> TASK-5373 - Error compiling opencga-enterprise - ClinicalAnalyst changes

- biodata-external/pom.xml
- biodata-formats/pom.xml
- biodata-models/pom.xml
- biodata-tools/pom.xml
- pom.xml
TASK-5425 - PortPatch 1.10.1 -> 2.0.0
> TASK-5425 - PortPatch 1.10.1 -> 2.0.0

- biodata-formats/pom.xml
- biodata-formats/src/test/java/org/opencb/biodata/formats/variant/annotation/io/VepFormatWriterTest.java
- biodata-models/pom.xml
- biodata-models/src/main/java/org/opencb/biodata/models/alignment/RegionCoverage.java
- biodata-models/src/main/java/org/opencb/biodata/models/clinical/pedigree/Pedigree.java
- biodata-tools/pom.xml
- biodata-tools/src/main/java/org/opencb/biodata/tools/alignment/stats/AlignmentGlobalStats.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/alignment/stats/SequenceKmers.java
- biodata-tools/src/main/java/org/opencb/biodata/tools/alignment/stats/SequenceStats.java
- pom.xml
TASK-4437 - Update general dependencies from dependabot (security alerts)
> TASK-4437 - Update general dependencies from dependabot (security alerts)

- biodata-external/pom.xml
- biodata-formats/pom.xml
- biodata-models/pom.xml
- biodata-tools/pom.xml
- pom.xml
TASK-5444 - Fix OpenCB repository versions to conform to XetaBase 2.0.0 version
> TASK-5444 - Fix OpenCB repository versions to conform to XetaBase 2.0.0 version

- biodata-tools/src/main/java/org/opencb/biodata/tools/alignment/BamManager.java
[TASK-5162](https://app.clickup.com/t/36631768/TASK-5162)
> Increase MAX_REGION_COVERAGE

- biodata-tools/src/test/java/org/opencb/biodata/tools/variant/VcfManagerTest.java
- pom.xml
TASK-5605 - Modification of CI/CD to run opencga and opencga-enterprise unit tests
> TASK-5605 - Modification of CI/CD to run opencga and opencga-enterprise unit tests

- .github/workflows/pull-request-approved.yml
- .github/workflows/scripts/get-xetabase-branch.sh
- .github/workflows/scripts/xetabase-branch.sh
TASK-6399 - CI/CD: Include save reports option for tasks workflows
> TASK-6399 - CI/CD: Include save reports option for tasks workflows

- .github/workflows/pull-request-approved.yml
- .github/workflows/scripts/get-xetabase-branch.sh
TASK-6807 - Pull request approve workflow Fail
> TASK-6807 - Pull request approve workflow Fail

- .github/workflows/pull-request-approved.yml
- .github/workflows/scripts/get-xetabase-branch.sh
- biodata-external/pom.xml
- biodata-formats/pom.xml
- biodata-models/pom.xml
- biodata-tools/pom.xml
- pom.xml
TASK-6879 - Adapt GitHub Actions, CICD workflows and release scripts to new SDLC
> TASK-6879 - Adapt GitHub Actions, CICD workflows and release scripts to new SDLC

- .github/workflows/test-analysis.yml
- biodata-external/pom.xml
- biodata-formats/pom.xml
- biodata-models/pom.xml
- biodata-tools/pom.xml
- pom.xml
[TASK-7589 - Port Patch 2.12.4 -> 3.2.3 Xetabase 1.10.9 -> 2.2.3](https://app.clickup.com/t/36631768/TASK-7589)
> TASK-7589 - Port Patch 2.12.4 -> 3.2.3 Xetabase 1.10.9 -> 2.2.3

- .github/workflows/pull-request-approved.yml
- .github/workflows/test-analysis.yml
[TASK-7693-dev - Upgrade Ubuntu image on GitHub Actions](https://app.clickup.com/t/36631768/TASK-7693-dev)
> TASK-7693-dev - Upgrade Ubuntu image on GitHub Actions

- .github/workflows/pull-request-approved.yml
- .github/workflows/test-analysis.yml
[TASK-7693-rel - Upgrade Ubuntu image on GitHub Actions](https://app.clickup.com/t/36631768/TASK-7693-rel)
> TASK-7693-rel - Upgrade Ubuntu image on GitHub Actions

- biodata-external/pom.xml
- biodata-formats/pom.xml
- biodata-models/pom.xml
- biodata-tools/pom.xml
- pom.xml
Automated portpatch from tag v3.6.0 to branch release-4.x.x
ClickUp Task: https://app.clickup.com/t/36631768/TASK-7843
> Portpatch 3.6.0 -> 4.1.0-SNAPSHOT
